### ISSUE TITLE
sim800c 里面的 at_socket_sim800.c文件中urc_recv_func函数为什么最后不用释放rt_free(recv_buf);

### ISSUE THREAD

**Issue by jinbangju** [RT-Thread-packages/at_device#131]
![图片](https://user-images.githubusercontent.com/24245481/90088337-4781cd80-dd51-11ea-9327-639ef99ceec4.png)

**Comment by Lawlieta** [comment]
接收的数据会先被挂载到数据接收列表中，然后 recvfrom  接收数据完成后会释放，所以这里不加 rt_free(recv_buf)
