### ISSUE TITLE
请问 PR 是否有具体格式要求?

### ISSUE THREAD

**Issue by OROKIN** [RT-Thread-packages/at_device#133]
想提交一个模块的支持至 at_device 中，请问 PR 是否有相关格式要求？

**Comment by xiangxistu** [comment]
与已有的模块支持代码，在风格上类似就行

**Comment by OROKIN** [comment]
> 与已有的模块支持代码，在风格上类似就行

好的 谢谢

**Comment by Lawlieta** [comment]
代码建议符合 RT-Thread 编码规范 https://github.com/RT-Thread/rt-thread/blob/master/documentation/coding_style_cn.md
