### ISSUE TITLE
Readme.md 中的 「laster」版本是否应该为「latest」？

### ISSUE THREAD

**Issue by ousugo** [RT-Thread-packages/at_device#135]
文档中多处出现「laster」
![image](https://user-images.githubusercontent.com/43401755/94529766-b6b57180-026c-11eb-8f1d-dc470ba414e6.png)
在 env 中为「latest」
![image](https://user-images.githubusercontent.com/43401755/94529836-d056b900-026c-11eb-8134-677a51f8367e.png)

**Comment by LXGMAX** [comment]
2333 你可以改正提PR😂
