### ISSUE TITLE
rt_delayed_work_init 已被移除

### ISSUE THREAD

**Issue by a1012112796** [RT-Thread-packages/at_device#164]
rt_delayed_work_init 似乎在master分支被移除了(https://github.com/RT-Thread/rt-thread/commit/94ed55f34d5f0fb6f086e84eecfe4ce3b635056f)
但在这个软件包中仍有使用,例如:
https://github.com/RT-Thread-packages/at_device/blob/28906922bded66bac35734b6da80b5d34a8b73b8/class/esp8266/at_device_esp8266.c#L614-L615
请问该如何处理?谢谢！

/cc @mysterywolf

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread-packages/at_device/pull/165

**Comment by mysterywolf** [comment]
@Guozhanxin 这个issue可以关闭了
