### ISSUE TITLE
AT socket esp8266 串口发不出指令，shell卡死

### ISSUE THREAD

**Issue by ygcaicn** [RT-Thread-packages/at_device#48]
AT socket esp8266

console用的uart2
at用的uart1
板子nucleo f401re
（f103我也试了同样的问题）

msh开机正常输出，提示AT client成功，然后理论上应该是uart1发送AT+RST，实际卡在这里，shell无法再输入任务东西

![1](https://www.rt-thread.org/qa/data/attachment/forum/201904/28/193732naqa58o8e1ajjrlo.png)

uart1连到串口，发现收不到任何东西

![](https://www.rt-thread.org/qa/data/attachment/forum/201904/28/193732qf97gbp5p4puf5z5.png)

调试，发现一直在等uart1发送完成标志：如下图

![https://www.rt-thread.org/qa/data/attachment/forum/201904/28/193732o8giplnnmoqy1bii.png](https://www.rt-thread.org/qa/data/attachment/forum/201904/28/193732o8giplnnmoqy1bii.png)

AT socket esp8266串口发不出指令
<https://www.rt-thread.org/qa/thread-10994-1-1.html>
(出处: RT-Thread开发者社区)

**Comment by Lawlieta** [comment]
先确定 esp8266 模块是否好使，可以直接使用串口工具连接 PC 端测试。

如果 模块收发数据没问题，确定该串口驱动是否正常，可以把 uart1 串口改变为 shell 口测试 uart1 是否正常。
