### ISSUE TITLE
更新at组件编译时发生错误

### ISSUE THREAD

**Issue by ruizhai1** [RT-Thread-packages/at_device#53]
更新at组件编译时发生错误
![at问题1](https://user-images.githubusercontent.com/49899780/58429653-2cd62100-80d9-11e9-9004-16494d9724ea.PNG)
D:\rt-thread\components\net\at\at_socket下的struct at_device_ops和D:\rt-thread\bsp\ls1cdev\packages\at_device-latest\inc下的struct at_device_ops重复
![at问题2](https://user-images.githubusercontent.com/49899780/58429832-bbe33900-80d9-11e9-8653-5cc30fd5dd1e.PNG)
![at问题3](https://user-images.githubusercontent.com/49899780/58429839-be459300-80d9-11e9-84ee-845fb919faa3.PNG)

**Comment by Lawlieta** [comment]
需要更新 RT-Thread 最新源码

**Comment by Ghazigq** [comment]
> 
> 
> 需要更新 RT-Thread 最新源码，最新源码发布了 AT 组件 V1.3.0 版本

我的也是这种问题，用的是V2.0.0的AT组件，内核4.0.1

**Comment by Lawlieta** [comment]
可以使用最新的 4.0.2 版本系统

**Comment by Ghazigq** [comment]
> 
> 
> V2.0.0 的 AT device 需要使用最新的 4.0.2 版本系统哦
好的
