### ISSUE TITLE
为啥没有具体指令？

### ISSUE THREAD

**Issue by zakigo** [RT-Thread-packages/at_device#71]
例如ESP8266的AT+CWLAP指令都没有

**Comment by Lawlieta** [comment]
直接调用 at_device_control 函数可以设置 WIFI 账号密码，可以直接封装导出命令，可以查看如下代码：

https://github.com/RT-Thread-packages/at_device/blob/master/class/esp8266/at_device_esp8266.c#L847-L913

**Comment by zakigo** [comment]
哦哦，你们这个包只需要联网就可以实现socket通信。我理解错了，我以为是完全控制AT设备
