### ISSUE TITLE
SIM76xx SIM Card Check

### ISSUE THREAD

**Issue by HikerPan** [RT-Thread-packages/at_device#90]
`for (i = 0; i < CPIN_RETRY; i++)
        {
            at_obj_exec_cmd(client, resp, "AT+CPIN?");
            if (at_resp_get_line_by_kw(resp, "READY"))
            {
                LOG_D("%s device SIM card detection failed.", device->name);
                break;
            }
            LOG_I("\"AT+CPIN\" commands send retry...");
            rt_thread_mdelay(1000);
        }`
上面的代码中LOG_D部分的打印信息反了，这个逻辑应该是success，不是failed

**Comment by Lawlieta** [comment]
你好，问题已经确定，确实是日志显示错误，近期会修复

**Comment by Lawlieta** [comment]
已修改 https://github.com/RT-Thread-packages/at_device/pull/108
