### ISSUE TITLE
rtthread中使用有人WH-LTE-7S4模块

### ISSUE THREAD

**Issue by xiaofyao** [RT-Thread-packages/at_device#99]
我已经成功移植了AT包和AT socket包，请问rtthread当前支持使用有人WH-LTE-7S4模块吗？

这个模块是工作在串口透传状态的，直接通过串口发数据到模块，然后模块将数据封装成TCP包发送給服务器。

我想基于这个模块在rtthread上使用MQTT协议，请问这个方案可行吗？

**Comment by armink** [comment]
透传就没法基于 socket 进行传输了

**Comment by xiaofyao** [comment]
请问有啥其他方案可以基于这个模块，使用mqtt协议吗？

这个模块也可以设置成httpd模式和udc模式
 @armink

**Comment by armink** [comment]
模块本身得支持 AT 指令模式，能够同时使用多个 socket 就行

你可以对比看下，已经支持的模块的 PDF

**Comment by xiaofyao** [comment]
这个模块可以同时使用两路socket，两路socket可以同时连接不同的服务器，请问大神这个模块和已经支持的哪个模块最相近？我好参照下 @armink

**Comment by armink** [comment]
你就参考 EC20/AIR720 这类 4G 模组就行
